### ISSUE TITLE
Aggregate Style Info

### ISSUE THREAD

**Issue by figital** [ragamufin/nodedump#1]
Would be awesome to extract the inline styles into an external config file ... whether that is a runtime/included CSS .. referenced at another URL ....or some combination.
(feature request)

**Comment by ragamufin** [comment]
Totally agree, was thinking about it myself as I put this together but couldn't figure out a simple way to have the style tag output just once per request if the dump is used. Any ideas?

**Comment by figital** [comment]
oops ... didn't know that wasn't an email thread. will try to play around with this ... fun stuff.

**Comment by ragamufin** [comment]
No problem, let me know whatever you come up with. I'll close this as an issue for now.
