### ISSUE TITLE
how to show "projects.name" only in your nodedump(user) sample ?!?

### ISSUE THREAD

**Issue by Abdelkrim** [ragamufin/nodedump#3]
Hi @ragamufin , 

is there a way to 'show' the fields "projects.name" only in your sample "nodedump(user)" ?!?

your package is awesome! unbeatable for the debug

**Comment by ragamufin** [comment]
Thanks for the comments!
Hmm, the closest thing to achieve what you're asking would be something like:
`nodedump(user, {show: ['projects', 'name']});`

**Comment by ragamufin** [comment]
I spoke too soon. `show` and `hide` only affect the top level keys when dumping. In a case like the one you want I'm guessing you could simply `console.log` it since you know what you're looking for or simply do: `nodedump(user.projects)`

**Comment by Abdelkrim** [comment]
Good idea.  Thx
