### ISSUE TITLE
How to call nodedump from the front end? 

### ISSUE THREAD

**Issue by Abdelkrim** [ragamufin/nodedump#4]
Hi @ragamufin ,

could you please add a section in the documentation explaining how to call nodedump from the front end ?!? 

I would like:
1. to send the json file to the browser and then 
2. let the browser parse the json file and display it using nodedump.

Thank you in advance for your help,

**Comment by ragamufin** [comment]
Hmm, right now it is built to run server-side but I guess with a little tweaking it can run client-side as well. I'll take a look when I have a moment and get back to you if it's possible. Thanks for the idea.

**Comment by Abdelkrim** [comment]
Thanks for the feedback but I have found prettyprint which does exactly start nodedump does on the client side : https://github.com/padolsey/prettyPrint.js

**Comment by ragamufin** [comment]
Awesome. Let me know how it works for you. I will still try and put in client-side functionality into nodedump as I think your idea was a good one

**Comment by ragamufin** [comment]
Just to let you know. The ability to use nodedump client-side has now been added. See: https://github.com/ragamufin/nodedump#client-side on how to use it

**Comment by Abdelkrim** [comment]
Awesome! thanks !

## 

Abdelkrim Boujraf
http://www.alt-f1.be

## Founder, MBA

blog | twitter | linkedin
