### ISSUE TITLE
Can not display Array with use string, not index

### ISSUE THREAD

**Issue by chinh-nguyen** [ragamufin/nodedump#5]
Can not display Array with use string, not index. For example:
var attributes = new Array();
            attributes['inspectorname'] = {
                value: "John"
            };
document.write(nodedump(attributes));
Above function will just show that the Array is empty

**Comment by ragamufin** [comment]
haha, you're just asking for trouble aren't you? I guess that is something that's allowed with JavaScript so it should be accounted for. I've updated the code and this should be working now.

**Comment by chinh-nguyen** [comment]
Thanks for your quick update ragamufin, I tested and it work well

**Comment by ragamufin** [comment]
You're most welcome!
