### ISSUE TITLE
Reference local file in the script file

### ISSUE THREAD

**Issue by chinh-nguyen** [ragamufin/nodedump#6]
Thanks for your great tool, I just found another bug in your script, you are reference the local file in your machine as below:
D:\Andrew\DropBox\Private\Work\nodedump\node_modules\browserify\node_modules\insert-module-globals\node_modules\process\browser.js

**Comment by ragamufin** [comment]
Thanks for finding this. I've updated the code and removed references to my local files. Let me know if you run into anything else.
