### ISSUE TITLE
How to get a readable dump from the min+map client js file?  

### ISSUE THREAD

**Issue by xuming314** [ragamufin/nodedump#9]
nodedump-client is usefull for released client's environment.
but released client is usually use minimum js.
how to get a readable dump from the min+map client js file?

**Comment by ragamufin** [comment]
I'm not sure I understand your question. Could you give me an example or explain a bit further?

**Comment by xuming314** [comment]
my client js is use uglify to generate a "minification js" and a "sourceMap js".
when minification js happen error, I will catch error and use nodedump-client to generate errDump string. and send to server.
In server side, I want to use sourceMap parse "minification errDump string" to get a "readable errDump string".

**Comment by ragamufin** [comment]
hmm, I still don't get it. Can you post an example or send me the files and show what you're trying to do?
